name: "Terraform CI/CD Pipeline"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  # CRITICAL: Required for GitHub Actions to request the OIDC JWT token
  id-token: write # Required for requesting the JWT

jobs:
  terraform:
    name: "Terraform Automation"
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.0"

      # 3. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          #role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubActions-Terraform-Role

      # 4. Initialize Backend (S3) & Providers
      - name: Terraform Init
        id: init
        run: terraform init

      # 5. Check Code Formatting
      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check

      # 6. Generate Execution Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      # 7. Apply Changes (Runs ONLY on direct pushes/merges to main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve